baseURL = "http://localhost:1313/"
languageCode = "en-us"
title = "Reference Repo"
subtitle = "a collection"
theme = "simple2"
buildDrafts= true

[taxonomies]
  tag = "tags"
  category = "categories"
  format = "formats"